# Generated by Django 4.1 on 2022-08-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=50, verbose_name='Name')),
                ('CommercialQty', models.IntegerField(verbose_name='Commercial Quantity')),
                ('AdviceQty', models.IntegerField(verbose_name='Advice Quantity')),
                ('CommercialImagesQty', models.IntegerField(default=0, verbose_name='Commercial Images Quantity')),
                ('CreationDate', models.DateField(auto_now=True, null=True)),
                ('CreationTime', models.TimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name_plural': 'Propietaries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceName', models.CharField(max_length=50, verbose_name='ProvinceName')),
                ('ResumeProvince', models.CharField(max_length=140, verbose_name='ResumeText')),
                ('LongTextProvince', models.CharField(max_length=140, verbose_name='LargeText')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworksGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='SocialName')),
            ],
        ),
        migrations.CreateModel(
            name='ProvincePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/province')),
                ('ResumeTextIamge', models.CharField(max_length=140, verbose_name='ResumeText')),
                ('SubIndex', models.IntegerField(default=0, verbose_name='Index Picture Order')),
                ('Province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.province', verbose_name='Province')),
            ],
            options={
                'verbose_name_plural': 'Province Pictures',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PropietaryPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/province')),
                ('ResumeTextIamge', models.CharField(max_length=140, verbose_name='ResumeText')),
                ('Propietary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.propietary', verbose_name='Propietary')),
            ],
            options={
                'verbose_name_plural': 'Propietary Pictures',
            },
        ),
        migrations.AddField(
            model_name='propietary',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='propietary',
            name='User',
            field=models.OneToOneField(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='plan',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommercialName', models.CharField(max_length=50, verbose_name='Name')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('CommercialEmail', models.EmailField(max_length=254)),
                ('User', models.OneToOneField(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.propietary', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Commercial',
            },
        ),
    ]
