# Generated by Django 4.1 on 2022-08-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='CommercialImages',
        ),
        migrations.AddField(
            model_name='plan',
            name='CommercialImagesQty',
            field=models.IntegerField(default=0, verbose_name='Commercial Images Quantity'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='AdviceQty',
            field=models.IntegerField(verbose_name='Advice Quantity'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='CommercialQty',
            field=models.IntegerField(verbose_name='Commercial Quantity'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='PlanName',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Status'),
        ),
    ]
