# Generated by Django 4.1 on 2022-08-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietary',
            name='User',
        ),
    ]
