# Generated by Django 4.1 on 2022-08-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_plan_commercialimages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='FechaCreacion',
            new_name='CreationDate',
        ),
    ]
