# Generated by Django 4.1 on 2022-08-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_status_options_propietary_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'verbose_name_plural': 'Commercial'},
        ),
    ]
